//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szafiarka.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=\"D:\\ONEDRIVE\\STUDIA\\INŻYNIERIA" +
            " OPROGRAMOWANIA\\PROJEKT\\SZAFIARKA\\SZAFIARKA\\DATABASE.MDF\";Integrated Security=Tr" +
            "ue;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string D__ONEDRIVE_STUDIA_INŻYNIERIA_OPROGRAMOWANIA_PROJEKT_SZAFIARKA_SZAFIARKA_DATABASE_MDFConnectionString {
            get {
                return ((string)(this["D__ONEDRIVE_STUDIA_INŻYNIERIA_OPROGRAMOWANIA_PROJEKT_SZAFIARKA_SZAFIARKA_DATABASE" +
                    "_MDFConnectionString"]));
            }
        }
    }
}
